### ISSUE TITLE
Invalid kernel size: 4198400 in WorkerForm.cs

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#10]
Trying to flash original on a "fresh" system with no cores or games.

- First flash of custom kernel fails with the below error

Notes:
1. I don't have a drive H: ?
2. It always dumps the kernel in this situation - should it?
3. Afterwards I cannot switch off the SNESC and have to pull the power cable!
4. Powering with a high power 3amp USB3.0 socket.

video
https://youtu.be/qMUDpj37ecU

error
```
Invalid kernel size: 4198400  at
com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in
H:\hakchi2\WorkerForm.cs:line 601
  at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in
H:\hakchi2\WorkerForm.cs:line 315
```

![screen shot 2018-02-07 at 12 06 20](https://user-images.githubusercontent.com/49612/35915579-5acec83c-0bff-11e8-8cdb-309e602a59c3.png)

console
[debuglog.txt](https://pastebin.com/raw/jYSj4q0f)

![screen shot 2018-02-07 at 11 56 42](https://user-images.githubusercontent.com/49612/35915584-5f514182-0bff-11e8-8b88-52443b012d15.png)

**Comment by KMFDManic** [comment]
Flashing Original should be used sparingly. But, have you attempted original after the uninstall, and before custom?

**Comment by gingerbeardman** [comment]
Why? 

I do it because the app prompts me to flash original as part of "uninstall".

Interesting: using fresh download hakchi2 CE 1.0.0 or hakchi2 CD 1.0.1 does everything OK.

So I guess I have something in my folder that is causing a problem?

**Comment by gingerbeardman** [comment]
OK, I have redone the video. flashing original is a red herring as it happens just doing "flash custom" see OP for new video and debuglog.

just doing "flash custom" with my particular install of hakchi2ce101, so what in my folder could be causing this to fail?

**Comment by KMFDManic** [comment]
Flash original should only be done if one triggers can't unpack ramdisk error or otherwise has problems with anything else, and, of course, for resells  Typically, in older hakchi2 versions, simply deleting temp folder and cleaning temp internet files would clean up house. In this case, just flash original, only if necessary to. I uninstall, cancel the flash of the original, because uninstalling retains the default games, anyways:)  Well, as long as you started with them previous to a custom flash.

**Comment by gingerbeardman** [comment]
Redid my hakchi2 folder completely from a fresh download and everything seems OK, very odd.
