### ISSUE TITLE
Cannot flash with 1.2.5

### ISSUE THREAD

**Issue by kdorff** [TeamShinkansen/Hakchi2-CE#111]
I'm running a very fresh install of Windows 10 Pro. 

I have an SNES class that had the original Hakchi2 installed. I followed the directions

http://snesclassicmods.com/how-to-switch-from-hakchi2-to-hakchi2-ce/

To perform the migration. Reverting the SNES worked fine (steps 1-6). The device is in a state that it boots up as originally purchased. 

I started step 7. It writes firmware. Gets to the point where the console is rebooting. And then tells me "Your device is taking a long time to boot.  You can wait...". When I look at the HDMI out of the console it has a big "Knock, Knock" "HAKCHI" "https://hakchi.net". So, as best as I can tell, it's probably booted?

I tried the above steps multiple times. With fresh extractions of Hakchi2 CE 1.2.5. No different in results.

I additionally tried installing Haichi2 CE 1.2.5, fresh extraction of zip, onto my NES Classic which was fresh out of the box. I got the EXACT same behavior.

**Comment by kdorff** [comment]
In short: I tried a different USB port and changed USB cables. It works!

* Before I was using a USB port on the front panel of my system (connected to the motherboard via a header, shouldn't make a difference, but who knows)
* I switched to a USB port on the back (directly connected to the motherboard)
* I changed USB cables
* I flashed both the NES Mini and SNES Mini with no issues

**Comment by TheRealIndru** [comment]
Any alternatives? I'm having the same problem, but your solution didn't work for me.

**Comment by karakenio** [comment]
You should try first:
- Change USB cables (use the Nintendo one)
- Switch USB port (a black USB 2.0, instead of a blue USB 3.0)
- Download/use Zadig program, to workout your USB port.*
* (I downloaded, but manage to resolve the issue before using it).

I went to an old Hatchi2 [2.1?]
I Sincronize, Asked me to flash -> I Did.
!! But I stopped it when it asked me to install the games. 

Then I went to my last version of Hatchi2 [CE v3.5.2 (Debug)]
Kernel -> Unnistall
!! Then 'Install/Repair' (I think this was what worked for me)
