### ISSUE TITLE
Getting "qsound" when importing MAME Roms

### ISSUE THREAD

**Issue by JasonBurnett** [TeamShinkansen/Hakchi2-CE#114]
When I try to import MAME Rom zip-files contain a file with a ".bin"-extension, Hakchi 2 CE does not show the usual prompt where I can select "import as archive" but instead assumes that the ".bin"-file inside the zip is the actual rom.
For example, when trying to import the game "Marvel vs. Capcom", there is a file called "qsound.bin" inside the zip and Hakchi 2 CE just imports it as "qsound" without any possibility to import the entire zip-file.

I already found a workaround for this: I kept the old Hakchi2 ver 2.20 installed on my PC. When I try to import the game there, the prompt does appear, and I can import the game as an archive. I then go into the "games_snes" folder of Hakchi2 (non-CE) and just drag and drop the game folder over to the corresponding subfolder of Hakchi2 CE. Then the game appears correctly in Hakchi2 CE, I can sync it over to the SNES mini and it plays just fine.

But still it would be nice if this import feature could be fixed (then I could finally delete the old Hakchi2 instance from my PC).

**Comment by bslenul** [comment]
**EDIT**  
They added a feature in 3.3.0 `File > Add more Games > As-Is...`, which works perfectly fine for those problematic games 👍 

For info someone had the same kind of problem yesterday on the Discord but with a .u1 file.
The guy added a [**zip**](https://cdn.discordapp.com/attachments/426489336012210176/470710384270245908/screenshot.139.jpg) but since u1 extensions are also used by N64 cores I guess CE thought it was a N64 game and only imported this file!

Same solution as for the qsound.bin, you can just extract and remove the file from the zip before adding to CE and once it has been processed add it again in the zip.  
OR  
Just add a fake empty file with the same extension before adding to CE.
