### ISSUE TITLE
Allow ROMS to be added by double-click from file manager

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#13]
Right now I can associate ROMs with the app, hakchi2 will start but the ROM will not be added

**Comment by KMFDManic** [comment]
@gingerbeardman The expected behavior for hakchi is to generally allow the double click addition whilst the program is already open.  It would be nice to be able to have it associated with the hakchi.exe.  But, there are so many different extensions to account for, that whitelisting/blacklisting would be an insanely arduous task.  So, for now, while it is a fantastic suggestion and request, it won't be immediate priority.  But, it will be one of several other of your great ideas that will be potentially looked into and implemented!
