### ISSUE TITLE
Error when trying to install driver

### ISSUE THREAD

**Issue by chuckwalla123** [TeamShinkansen/Hakchi2-CE#132]
Has anyone encountered an error in trying to install the driver with the new Hackchi CE 3.4.1?
I get the following message, "The inf file does not support this method of installation"
I have the newest release of the NES Classic and am trying to flash it for the first time.
I do the process where the power button is pushed in and I hold the reset button so the LED light doesn't come on etc. etc.
Any suggestions?

**Comment by hauptstadtkind83** [comment]
Same issue :-( Using Windows 7 Starter (x86) and Professional (x64) shows me same error. Had to use driver package from hakchi2 CE 1.2.5 because 3.3.0, 3.4.0 and 3.4.1 does not work...

**Comment by talbeau** [comment]
Same issue, @hauptstadtkind83 Can you elaborate on how you used the older driver packages?

**Comment by daPhie79** [comment]
it does seem like the new driver package isn't windows 7 friendly. Here's the previous driver:
[nesmini_driver.zip](https://github.com/TeamShinkansen/hakchi2/files/2320908/nesmini_driver.zip)

**Comment by i0brendan0** [comment]
I'm having the same issue with my SNES classic but the driver @daPhie79 gave is for the NES classic. Is there another one for the SNES classic? Yes I'm on Win 7 as well.
 
[EDIT] Sorry, I guess I fixed it. I copied the driver installer from the one from like 9 days ago to where the old one is. But I guess when you try to use the Save thing, the file it goes to isn't there. That's why I thought I had a problem.
