### ISSUE TITLE
Issues scanning for box art

### ISSUE THREAD

**Issue by DNA64** [TeamShinkansen/Hakchi2-CE#140]
1. When selecting "Scan for new box art for selected games" for the title "M.U.S.H.A", H2CE becomes unresponsive.

2. When scanning for box art, if a ROM was titled "Bass Masters Classics"
and the artwork was "Bass Masters Classic (USA).png" the system wouldn't find the artwork nor suggest any possibilities, unless you rename the ROM "Bass Masters Classic".

**Comment by daPhie79** [comment]
1. was there any output in the console window, because i can't make this happen on my end.

2. i think this is intended, as the search is tuned to allow more vagueness in the cover files, not the other way around. when i was trying to make it work, if i was letting the possibility of matching vagueness on both ends, it made it VERY imprecise, making way too many games to precise. when an item isn't matched automatically, use browse... :)

**Comment by daPhie79** [comment]
correction, i was able to see the issue. it's a recursive test error. well. i didn't account for the possibility of a game being made of only dots. this causes the algorithm to test for each letter as a "word" against all files in your art/**/ directory. this causes MANY tests, lol. i will note this and fix when i can.

**Comment by DanTheMan827** [comment]
If you want long enough, it does eventually finish

![image](https://user-images.githubusercontent.com/790119/53666574-0caad900-3c34-11e9-92f7-e67c9deabe07.png)

**Comment by KMFDManic** [comment]
@DNA64 Thanks for the feedback on the box art scanning issues.  DanTheMan827 fixed it for the very next Release!  Thanks again:)
