### ISSUE TITLE
No Sound while using Capture Card

### ISSUE THREAD

**Issue by BouFrost** [TeamShinkansen/Hakchi2-CE#149]
Hello,
my problem is, when i use a capture card for capturing the footage, i have no sound on TV and PC.
Directly on TV, everything is fine. Capture card sound with original kernel also works.
To make it clear what i mean:

orig. kernel -> TV => Sound
hackchi2 kernel -> TV => Sound

orig. kernel -> CapCard -> TV => Sound
orig. kernel -> CapCard -> PC => Sound

hackchi2 kernel -> CapCard ->TV  => no Sound
hackchi2 kernel -> CapCard ->PC  => no Sound

So it's seems as some kind of hackchi problem and not one of the system ...
It's like hackchi is adding some kind of HDMI protection to the system. Don't know how to solve that

**Comment by KMFDManic** [comment]
Have you tried capturing with one of the default games?  If it works on original kernel, best test would be a non RetroArch game.

**Comment by BouFrost** [comment]
nope everything is mute, even the menu and all. it's really strange

**Comment by DanTheMan827** [comment]
Does this still happen with the latest version of hakchi?

I think some stuff was changed in the kernel related to sound

**Comment by KMFDManic** [comment]
@BouFrost This is a pretty common issue with AVerMedia Capture Cards, due to a variety of reasons.  Myself and others have found that Elgato Capture Cards are generally more reliable with the Mini NES/SNES, as well as the Nintendo Switch.  We can try to analyze your set-up a bit more.  But, this is likely something that may simply not be an easy fix.  Feel free to reply, if you want to try to run more tests, or if you've since resolved the conflict.
