### ISSUE TITLE
Hakchi2 CE doesn't see the NES Mini

### ISSUE THREAD

**Issue by Edjuh82** [TeamShinkansen/Hakchi2-CE#179]
Windows 10 sees the NESC (clv-s nesy) but Hakchi2 CE won't see it. When i reset + power button the NESC it shows up as NES Classic or Classic but still Hackchi CE won't see it.

I have a first gen NESC european version.

How can i fix this issue or is it a bug?

**Comment by Edjuh82** [comment]
Strange part is that the old Hakchi does see the nes mini when i flash it with that program.

**Comment by biogerm** [comment]
similar problem here with hakchi ce 3.5.2 and SNES mini

**Comment by MIRK0** [comment]
I have the same problem. Haktchi CE 3.5.2, Win7 64bit, SNES mini cannot install drivers when powered up + reset button pressed. In USB Tree, it can be seen
USB\VID_1F3A&PID_EFE8&REV_02B3
USB\VID_1F3A&PID_EFE8
Also tried Zadig 2.4, but it cannot even install driver WinUSB (v6.1.7600.16385)

**Comment by edrozenberg** [comment]
In my case, for the Kernel Install/Repair step, I had to use the Debug version of the Hakchi application. For some reason, the regular/installed Hakchi version did not work as far as having the console USB drivers recognize the console properly.

After the kernel installation, for later game update tasks I could use the regular (non-debug) Hakchi app.

So would recommend trying: download the latest Debug version of the Hakchi app (for ex. hakchi2-ce-3.5.2-debug.zip), run it, do the Kernel Install/Repair with it, then hopefully it will recognize the console for game updates afterwards.

**Comment by Edjuh82** [comment]
Nope doesn't work. Sadly this hakchi2 isn't working properly for me.

**Comment by biogerm** [comment]
It seems hakchi disables wifi while trying to talk to the console, which somehow is incompatible with the VPN service i'm using. in another word, the console disappears a short while after connected to the computer.

the solution to me, is to disconnect the console, reconnect the VPN service and plug the console back again. by doing this, i would have a very brief time to sync hakchi repo to the console before it disappears from hakchi again.

In the end, i chose to use a usb storage based hakchi to store the games, it's both much larger 64GB+ and no network issue any more since I don't connect the console to computer anymore. It works very well.

**Comment by KMFDManic** [comment]
@Edjuh82 If you still have any issues, let me know.  But, you should be able to do a fresh install of Hakchi2 CE, ensure you allow the firewall permission when prompted, use official micro USB cable that came with the system, in a viable USB Port on your PC, and install/repair kernel, to get the drivers appropriately installed.

@biogerm @MIRK0 @edrozenberg Hope things are all sorted out for you, as well!  Feel free to respond if you need any followup!
