### ISSUE TITLE
[[[ Feature Request ]]] Add SdPrep and Memory Booster to Hakchi

### ISSUE THREAD

**Issue by Cylent1** [TeamShinkansen/Hakchi2-CE#194]
Add SdPrep and Memory Booster menu options to Hakchi .
Thank You!

**Comment by DanTheMan827** [comment]
I would prefer to not bundle mods with hakchi2 ce itself for various reasons, and given that memory booster and sd prep are in fact mods, I believe they should stay in the mod store / mod hub.

when #196 makes its way to the code, there will be a image that will need to be flashed to the SD card like you would if you were using a raspberry pi or similar sbc if you want to boot from it.

**Comment by KMFDManic** [comment]
Zram Crash Inhibitor is safely worked into Hakchi2 CE, and works directly with the kernel, whether or not you are on USB-HOST.  Memory Booster requires a Card/Flash Drive, etc.  There is also a variable of how fast or slow the OTG/drive is.  You can still easily add Memory Booster, separately.  And, it works in conjunction with Zram.  But, as far as adding it into Hakchi...due to its variables, it is best left as a separate HMOD. 

SD Prep is a great idea.  It may have a very solid chance of working out, respectively, as an addition.  Thanks for the suggestions and feedback!

**Comment by DanTheMan827** [comment]
Format SD card will be an option under the tools menu in the next version

Also included will be an option to make the SD card bootable, this will allow everything to be stored on the card including retroarch cores and any other hmods

![image](https://user-images.githubusercontent.com/790119/58753506-b3964f80-8485-11e9-8d8a-1cf2ca733911.png)
