### ISSUE TITLE
OriginalGamesPosition doesn't sort the same way as sortRawTitle

### ISSUE THREAD

**Issue by ShizCalev** [TeamShinkansen/Hakchi2-CE#2]
OriginalGamesPosition in sorted mode parses `The` as the start of the name of a game's title, which differs from the behavior of custom added games

https://github.com/TeamShinkansen/hakchi2/blob/50f1ae80bb372ae98b769789eef8ac9fd75b65ad/Apps/NesMiniApplication.cs#L622-L624

**Comment by daPhie79** [comment]
try changing a character in the title of those games, and you can even set it back to its original name, then try refreshing the view with F5. tell me if it works! there's an issue because nintendo's own .desktop files come with their sort name field not removing the "the".

**Comment by daPhie79** [comment]
so i tested in the games list, with or without app grouping, with original games at the top or the bottom, or sorted, and games starting with the are properly sorted. original games may require "touching" the data to trigger the .desktop saving, because of Nintendo didn't exclude the "the" in their own stock files.
