### ISSUE TITLE
Multiple Games folders that can be combined into one folder

### ISSUE THREAD

**Issue by JWPepperSheriff** [TeamShinkansen/Hakchi2-CE#209]
hakchi has multiple games folders that are redundant. Can easily be combined into a single Games folder. 
games = 726 items
games_cache = 72 items
games_originals = 122 items

1)  games_originals was a neat idea but maybe 1% of Users care about separating Original Games out after they've added 900 other games to their Mini. 

2) games_cache folder, does this serve a useful purpose or can everything in this folder be rolled into games folder.

Purpose of consolidating games folders is to achieve a clean folder structure and create more simplicity.

![Capture](https://user-images.githubusercontent.com/48074076/54254356-68713e00-4521-11e9-8ed5-69f486d8fa46.PNG)

**Comment by DanTheMan827** [comment]
those folders aren't so much about separation for the user, but more so due to how ce functions

`games_cache` is an exact copy of the original games from the system that ce uses for when you export games to usb and tell it to copy the originals instead of linking them
`games_originals` is just the .desktop files so that CE has them to display them in the list before any system is connected, it's also where it puts custom art for the original games I believe

**Comment by KMFDManic** [comment]
Consolidation had already been done awhile back, as they used to actually be games and games_snes  The cache and originals folders serve the purpose that Dan mentioned.  It is pretty optimal for now.  But, things may be considered in the future as far as any further consolidation.  Thanks for the audit and feedback, though!
