### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by colther** [TeamShinkansen/Hakchi2-CE#224]
Can develop a support 50th jump fc crack hakchi？ My machine （jump fc）can't use this software，not support！please help me

**Comment by colther** [comment]
[

![](https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1475079211,868426355&fm=26&gp=0.jpg)
](url)

**Comment by KMFDManic** [comment]
@colther Can you better explain the exact issue you are having?

**Comment by colther** [comment]
Hello, my English is not good, please forgive me for using the translation software to translate the following text.What I'm saying is I bought jump50 anniversary version of the mini fc, but use the software hakchi2, prompt console kernel only American and Japanese version of the fc and SFC, the version is not I, now, my game consoles are unbreakable, no add games to play, I'm upset, developers can add the 50th anniversary of the updated version of the kernel to crack

**Comment by KMFDManic** [comment]
@colther Hakchi has support for the Shonen Jump.  You merely need to use the latest Hakchi2 CE, and install/repair kernel.  That should get you into action.  Also, make sure to click ok if a firewall prompt opens on first usage.  I recommend using debug version, which is what works great for me!  Kernels already exist on the system, and are safely backed up by hakchi.  So, they are not really necessary unless there are special circumstances where you attempted to mod with an older or non-supported Hakchi.

**Comment by colther** [comment]
@KMFDManic Hello, thank you very much for solving this problem that has puzzled me for a long time. I will try to crack it when I go back. If it succeeds, can you tell me where I can download the game ROM? I want to save a lot of interesting games to the computer, thank you

**Comment by KMFDManic** [comment]
@colther Glad your issue is resolved.  Unfortunately, it is a "grey" area, when it comes to roms.  We cannot link to them.  But, if you go to Modules Tab within Hakchi, then KMFD Mod Hub, Games Tab, I have several games you can directly download that "are" legal.  The "prerequisite" is what Core you will need to have to run them.  I have will continue to add more in the future:)  Closing this issue.  If you need any assistance running any of the Cores/Games, feel free to respond, or join us on Discord:)
