### ISSUE TITLE
Customizable location of Hackchi games folder

### ISSUE THREAD

**Issue by ianheat83** [TeamShinkansen/Hakchi2-CE#232]
Hi there,

I’ve been trying to find an option to have the games which are stored for transfer to my snes mini to be kept in a location other than “my documents”.

I have a lot of ps1 games I would like to use with snes mini, and I’m also the kind of person that likes things to be setup, “ready to play” whenever I feel the need...

The required space to keep all ps1 games I want access to on my snes mini, on my computers main windows SSD to allow me to send the data to the snes mini would be quite large, and so I don’t believe I could put them all into “my documents” via adding to hackchi, to be able to then transfer them all, due to the fixed location of the games folder... I would have to free up space from the c: by deleting some games from hackchi that I don’t want to play for a bit, and then add the desired games to hackchi, to then export to USB for me to play on my snes mini... this would then lose all of my nice pictures for the games etc.

ideally I would like to be able to choose a location on a separate storage drive for the folder containing all of the required hackchi game structure to live more permanently, and allow me to have as much content as the USB stick for the snes mini (or my storage location) allows.

Is this a possibility or is there somewhere i can change the config to allow the games folder to live elsewhere than my docs? Or have I missed something in the setup :)

Thanks!

Ian

**Comment by DanTheMan827** [comment]
if you install the portable version or just download the zip file and extract it, that will keep everything in that folder, that will let you move it wherever you want.

if you're using USB for the classic, you can even put hakchi on the usb drive and use what is called linked export, this will create links to the games that are already stored on usb instead of copying them, as you can imagine, this is quite a bit faster.

You can also move your documents to a different drive if you prefer by right clicking on the folder, properties, then the location tab.

**Comment by ianheat83** [comment]
:) both sound like great options, I’ll check out the USB one, sounds ideal...

Thanks for the quick response and hard work, sorry I didn’t know about these other legitimate options.

Thanks again.
