### ISSUE TITLE
driver installation

### ISSUE THREAD

**Issue by yyrahmo** [TeamShinkansen/Hakchi2-CE#234]
**Describe the bug**  
driver installation has an error while connecting the device on the first time on win 7 x86
on the window where you are supposed to hold the reset button

Using the debug version :

SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
.........Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-123
........Executing task: MembootTasks.WaitForFelOrMembootableShell
System.UnauthorizedAccessException: L'accès au chemin d'accès 'installer_x86.exe' est refusé.
   à System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   à System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   à System.IO.Directory.Delete(String path, Boolean recursive)
   à com.clusterrr.hakchi_gui.TempHelpers.doWithTempFolder(Action`1 func, Boolean deleteAfter) dans C:\Users\daniel\Documents\GitHub\hakchi2\TempHelpers.cs:ligne 32
   à com.clusterrr.hakchi_gui.WaitingFelForm.InstallDriver() dans C:\Users\daniel\Documents\GitHub\hakchi2\WaitingFelForm.cs:ligne 38
Tasker completed all tasks, conclusion: Abort

**Comment by KMFDManic** [comment]
Not necessarily a bug.  This would typically be a conflict due to firewall/virus protection false positiving hakchi2 and/or driver installations as harmful, when they are in fact not.  On first open of a freshly extracted hakchi2, make sure you click ok to the firewall permissions.  Use micro usb cable that comes with the system, and kernel repair/install (hold power+reset simultaneously til progress bar starts to move).  Drivers will generally install in conjunction with this process.  Then, you should be good to go on synching/exporting.

**Comment by corners3** [comment]
Dude this helped me . Thank you
