### ISSUE TITLE
Your Device is taking too long to boot

### ISSUE THREAD

**Issue by Stallowned** [TeamShinkansen/Hakchi2-CE#246]
Greetings,

I've heard the NES/SNES Mini Hacking-Scene is as dead as a doornail so I will most likely not getting any help here. But if there is still anybody here it would be cool if anybody read this.

First things first, it's a shame Hakchi 3.5.3 will most likely be the last version ever released for the Minis. Really enjoyed your support.

So, yeah, guess the "Your system is taking too long to boot" is a known issue. Normally, I'm fine with the around 70 games on my SNES Mini. But there are a little few not performing perfectly. So I've updated Hackchi to 3.5.3. Since this update, I cannot flash the Kernel anymore.

It works till 28 percent and then nothing happens when the system is booting.. Hackchi tells me it's taking too long to boot, try again later.

In the last 2-3 months since I try it to get it to work I've done the following steps which worked for a few people it seems:

- Tried it at least 50 times or more
- Tried it with 5 different USB-Cables including the one you get with the SNES Mini
- Tried it a dozen times on every of my three USB-Ports on my Laptop
- Tried it on two complete different Laptops
- Tried it with my Windows Firewall completely deactivated
- Tried it with a new driver for the SNES Mini via Windows
- Tried it with Zadig which almost broke my SNES Mini
- Tried it via holding the Reset Button (it's not even connecting with Hakchi then)
- Tried it while disconnected from the Internet

What I haven't tried was updating the Kernel while dancing in the rain nude and holding a Pineapple in the left and an Orange in the right hand and singing "You don't fool me" from Queen.

Trust me I've read all the problem threads on Reddit, Redup and so on. I've most likely tried every crazy stuff the people wrote there. Nothing worked. I guess some Windows 10 Update is to blame here. Most likely the same Windows 10 Update which caused my Bose Speaker to not working properly anymore while connected on my Laptop.

If there is any solution I haven't adressed here, please let me know I would really, really appreciate it. I will not do something again that may break my SNES Mini though. Like I said my SNES Mini, like my NES Mini, is flashed I simply cannot use the most current version of Hackchi. Have tried the versions before 3.5.3 and when I update them to 3.5.3, the same stuff happens.

Best wishes from Germany.

**Comment by DanTheMan827** [comment]
I plan to release at least one more version of Hakchi2 CE, I've just been preoccupied, but yes, interest in the Nintendo classics has died down considerably since they've become quite difficult to find outside of the second-hand market.

This message is caused when Hakchi2 CE loads the boot image into memory and then waits for the system to start up and come online so it can run additional commands.

This as you've seen can be troublesome on some computers, it's especially a problem with virtual machines.

First of all, go into Hakchi2 CE and start the installation process.

**If you're running a virtual machine:**
There will be a second device you need to pass through after Hakchi2 CE loads the initial boot image, this is the device that it's waiting for.

If you're using VirtualBox, you'll also need the extension pack [which you can find here](https://www.virtualbox.org/wiki/Downloads)

**If you aren't running a virtual machine**
First, check the device manager to make sure there aren't exclamation marks on any device.

Next, check under network adapters  for anything resembling "Samsung classic" or "classic", if you see either of these, right click on them, select update driver, browse my computer for driver software, let me pick from a list of available drivers on my computer, and then select Microsoft Remote NDIS and click next.

After the driver installs, Hakchi2 CE will probably see the classic and continue automatically.

If you'd prefer to have a conversation about this instead of continuing in this issue, feel free to join our discord server https://discord.gg/C9EDFyg

**Comment by shinodark** [comment]
I got exactly the same problem. In debug, it ends up with "Unable to connect to the SSH server".
I fix it by completly uninstalling my vpn application, in order to remove all its network adapters installed on the system, and hakchi works great again.

**Comment by impeeza** [comment]
The hakchi, emulates a USB Ethernet adapter when connecting to computer. You must have a drivers problem.  Try to locate the new NDIS network adapter when connecting the NES Classic.  If doesn't show or show a driver error use the instructions on page for manually install the driver

**Comment by impeeza** [comment]
at the "\driver" folder of "hakchi2-ce-3.8.0-release.zip" there is a installer: "classic_driver.exe" you could use to manually install the drivers, old versions of Hakchi uses others drivers, you may be need to uninstall old drivers before new ones works.

**Comment by DanTheMan827** [comment]
those drivers are for FEL mode, that isn't the problem here, if it was you'd get a completely different error.

The problem is that VPNs like to grab any and all network traffic to prevent things from going onto the internet directly, this also has the side effect of taking all the network traffic destined for the classic and trying to incorrectly route it through the VPN.

If you don't have a VPN but still have this problem, windows may have incorrectly installed the RNDIS driver, or you may have an issue where the classic isn't receiving enough power and is crashing.

I've also seen cases where the DNS server given by an ISP was trying to be helpful and redirected the request to one of those search pages
