### ISSUE TITLE
SNES kernel bad dumped

### ISSUE THREAD

**Issue by caspericia** [TeamShinkansen/Hakchi2-CE#254]
Good morning and thank you in advance. I'm sorry for my English if I make mistakes because I'm from Spain. This is my trouble: While i was using the P-uae Extrem (Friend) and PPSSPP extreme (PSP) I had some problems in my configuration (overrides), so when I go to do a Factory reset I think I inadvertently dumped my console before the Factory reset so I understand that in the latest version of the hakchi ce 3.5.3 saves it somewhere so you can reinstall it later. The problem I have is that since that momet, when i try doing a Factory Reset or formatting the console kernel and having to "install/repair" again the kernel so you can put new games and cores the machine have a mistake. When I install the kernel I dumped (dumped) with some cores and games in particular (I used the retroarch 1.7.7 extreme), always takes me to that point, so I can't update anything, though apparently I installed the new ones. I have tried to put an original kernel inside a folder "dump" inside the hakchi, but in the latest version it does not work... I just don't know where my "wrong kernel" is to change it to an original one. I'll have to try uninstalling everything and install a previous version of the hakchi to see if it lets me load an original kernel, but I don't know if I'll have the same problem. Right now, I have mixed all the versions and I get the same overrides. In fact, uninstalling the kernel and doing a factory reset gives me that the console only has 218.8 mg of space. Is there any way to completely clean up the latest version of hakchi to be able to install everything (original kernel included) from the begining? Thank you and congratulations for your work.

**Comment by bslenul** [comment]
If you want to start over and be sure you're using correct kernel:

* Search and download a proper kernel, you can find the filenames here: https://web.archive.org/web/20190723140814/https://wiki.hakchi.net/Boot_Image  
(since you're Spanish I'm assuming you have a EUR console? If so, search for one of the `kernel-dp-sneseur-release-v2.0.xxx.img` file, the version doesn't matter). You'll have to find it yourself, we're not allowed to share those :(
* Open hakchi CE and click "Kernel" menu.
* **HOLD** Shift key on your keyboard and click "Uninstall".
* Wait a few seconds for the process to start and you can release Shift key.
* If done correctly hakchi CE will ask you for a kernel file when it's almost finished, select the one you downloaded from the first step.
* Now you should be back to stock, you can now click "Kernel > Install/Repair" to reinstall the hack with a proper kernel!

**Comment by caspericia** [comment]
Thanks a lot. I´ll try it as son as posible.
