### ISSUE TITLE
LOST MY ORGINAL FILES

### ISSUE THREAD

**Issue by narrdemetrius** [TeamShinkansen/Hakchi2-CE#266]
my computer recently crashed and I lost access to my hakchi files. I want to add more games to my Nes but don't know how to do so without losing all the games I already put on it. is there a way to do this?

**Comment by DanTheMan827** [comment]
If you make a backup of your user data, you'll end up with a .tar archive that can be opened in 7zip

From there, you can extract the games, the location inside the archive will be hakchi/games

Inside there will be some folders, if there's a .storage folder all the games are in that, otherwise they're all in numbered folders

Copy the folders starting with CLV into the hakchi2 CE games folder and relaunch

Then you can reset the custom kernel and install the mods and sync your games

**Comment by narrdemetrius** [comment]
how do I make a backup?

**Comment by DanTheMan827** [comment]
![image](https://user-images.githubusercontent.com/790119/68130411-ec2cd000-fee0-11e9-9e4e-ab9399922b9a.png)
