### ISSUE TITLE
SD mode - Syncing with just folder layout changes SOMETIMES triggers full re-write of SD card

### ISSUE THREAD

**Issue by TheTrainGoes** [TeamShinkansen/Hakchi2-CE#28]
When syncing via SD card, and just changing the folder structure or location of games within folders, 1.1.0 sometimes makes the changes, and sometimes rewrites the entire SD card.

Adding at least one new game and then making the changes to the folders also sometimes triggers a new write of the entire SD card.

**Comment by skogaby** [comment]
Hey,

Basically, in order to maintain speed for the differential syncs, we don't properly detect that files were re-arranged. Essentially, we go by filepath / filesize / last modified time. If any of those are different, it deletes the remote file and syncs over the local file. This will hopefully become more intelligent in the future, but as of now, this is basically by design.

**Comment by TheTrainGoes** [comment]
Thanks for the follow up!  Fantastic work
