### ISSUE TITLE
Audio problems on SNES games

### ISSUE THREAD

**Issue by Dominator593** [TeamShinkansen/Hakchi2-CE#288]
The problem I'm having really only applies to one Super Nintendo game, which would be Super Smash T.V. It sounds OK for a few moments, but then the audio only plays what sounds like only 1 sound channel. No voice samples, nothing.

**Comment by KMFDManic** [comment]
@Dominator593 did you try this on more than one SNES Core?

**Comment by KMFDManic** [comment]
@Dominator593 This isn't a hakchi issue.  A few games, here and there, have issues on SNES RetroArch Cores.  In the case of Smash TV, I would suggest trying it on SNES9x 2005 or 2010, where it should work fine.  Sometimes, games can slip through the cracks.  And, in fact, Smash TV had issues on my MAME 2003 Xtreme, of which was fixed up in a recent Release.  Feel free to bump this post with more info and test feedback, if you still have any issues on Smash TV.  As of my test, latest Release, game was running fine for me.  So, it might also benefit you to use a "different" rom, as a second opinion.  And, I greatly appreciate any and all feedback on games that have weird behavior, as I can try to get fixes hardcoded into the Cores to account for them.  Again, this is NOT a hakchi issue.  But, since I follow the issues here, I can keep tabs on your followup, and fix things, if need be:)
