### ISSUE TITLE
Instruction clarity

### ISSUE THREAD

**Issue by MegaMech** [TeamShinkansen/Hakchi2-CE#350]
Please change the wording of step 3 `Hold reset while pluggin in the cable`

to

`Hold reset while plugging in the cable until the flashing procedure initiates.`

**Comment by DanTheMan827** [comment]
I thought it was implied that it should be held until the dialog dismisses itself since it usually takes less than a second.

**Comment by MegaMech** [comment]
"Hold reset" literally means hold reset and do not let go. Doing so of course, ruins the flash. Wording matters.

**Comment by KMFDManic** [comment]
@MegaMech This is actually a bit of a misnomer, as the timing is quite different for MD/SNES/NES.  For SNES/NES, you can hold button indefinitely, and the flashing process will still occur.  And, you can let go once it starts, and it generally completes.  Mainly, on the MD Mini, you HAVE to let go the exact moment the Red LED turns off, OR the flashing process WILL fail.  Holding "reset" while plugging in the cable, is actually the ONLY guaranteed way that the flashing will work for all 3 Minis, since having it already plugged in, can be a conflict, depending on whomever's PC setup and security perimeters.  Hope that makes sense.  Let us know if you need anymore assistance:)  Closing this issue for now.

**Comment by MegaMech** [comment]
I believe you did not fully comprehend the issue as the second half of your comment discusses plugging in the cable. That part of the wording is clear and is not relevant to this issue. The part that's not clear is when to let go of the reset button.  

You described a variety of issues proving the wording is inaccurate and could be further clarified. Yet you disagree that the wording should be changed. Lets discuss this further.  

>  For SNES/NES... you can let go once it starts, and it generally completes
> on the MD Mini, you HAVE to let go the exact moment the Red LED turns off

Your comment proves that the current wording is wrong as both scenarios require letting go of the reset button. The instructions do not specify when to let go. Instead, they instruct the user to hold the reset button indefinitely.

> you can hold button indefinitely, and the flashing process will still occur

It will occur, but on the SNES the flash will fail if you hold the button indefinitely.

I recommend altering the wording to something like:
> Hold reset while plugging in the cable. Let go when the flashing procedure initiates.
or
> SNES/NES: Hold reset while plugging in the cable, let go when it starts.
> MD: Hold reset while plugging in the cable, depress as soon as the red LED turns off.

Reading between the lines is common practice. However, hardware flashing can lead to bricking if not done correctly. If you tell a user to hold the button, they are going to hold it indefinitely because not following the instruction risks bricking the device. Therefore, correct and concise wording of instructions is of extreme importance. All steps need to be listed, none can be assumed. Letting go of the reset button deserves to be a step four or clarified in step three. Please re-open the issue so that someone may submit a PR to fix this.
