### ISSUE TITLE
Turbografx 16 support

### ISSUE THREAD

**Issue by hossbags2** [TeamShinkansen/Hakchi2-CE#388]
When will turbografx 16 be supported

**Comment by KMFDManic** [comment]
This kind of support is not currently in the works, unfortunately.  Various combination of factors, including lack of interest, limited systems for "developers" to have, non FEL ability, with ease...due to no actual FEL Button (functioned ones), and so on.  I doubt it will happen anytime in the near future.  Luckily, it is a pretty badass system, on its own accord, regardless.  Most systems, IF modded, happen literally within a month or two.  Once interest wanes, it is far far less likely for devs to go back to them.  It would truly take someone who is dedicated and interested enough to have UART, and go through the pesky process of getting everything in order, so we can utilize custom kernel flashing (again, FEL hard buttons, not possible!  So, that can raise a few issues with stability).

**Comment by KMFDManic** [comment]
@hossbags2 This particular request is now known in our "main" topic.  If a hack comes forth for TG-16 Mini, rest assured, that main topic, listed here, will be updated accordingly:)

https://github.com/TeamShinkansen/Hakchi2-CE/issues/402
