### ISSUE TITLE
Sega Mini blank screen at boot with no hakchi boot screen or music

### ISSUE THREAD

**Issue by jamesonbone** [TeamShinkansen/Hakchi2-CE#389]
**Describe the bug**  
After installation of overclock mod unable to see home screen 

**To Reproduce**  
1. Boot Sega Mini
2. Blank screen

**Expected behavior**  
Home screen would appear after boot.

**Additional context**  
I did perform user partition format, was able to get to home screen and play games. This was all while still attached to PC. When I turn off Sega Mini unable to get back into home screen. If I perform install/repair or user partition format i can get into Sega Mini, but if power is turned off again I am present with blank screen on subsequent boot.

**Comment by DanTheMan827** [comment]
**Don't use this if you get a black screen and hear music**

**Absolutely do not use this on anything but a genesis mini / mega drive mini system!**

Since this is happening on a genesis mini, try this: [fixer.hmod](https://cdn.discordapp.com/attachments/572226560812122123/710284785578410054/fixer.hmod?ex=6a0ef801&is=6a0da681&hm=26b0ebe2d7ca3662c1a74749a2e94a8b2e308818f922f77b569b1babe8a7e44f&)

**Comment by jamesonbone** [comment]
Thank you for sharing the hmod. I Installed it and then performed install/repair of kernel. Im now able to boot into Sega Mini

**Comment by jamesonbone** [comment]
closing isue

**Comment by turbocomppro** [comment]
Hello. Any chance I can get the [fixer.hmod](https://cdn.discordapp.com/attachments/572226560812122123/710284785578410054/fixer.hmod)?
