### ISSUE TITLE
the problems ive had with hackchi over the past 4 years

### ISSUE THREAD

**Issue by hinson20** [TeamShinkansen/Hakchi2-CE#398]
here are my complaints about hackchi and what i think needs to be fixed
but first the problems:

1. everytime i load or mod anymore games a unknown file code error appears that makes no sense
2. unsupported nes games with incorrect mappers 
3. no unlimted storage
4. and everytime i save a game on the system it shows a random error that makes no sense
5. everytime i go to a game it just shows a gray or black screen

here is what i think needs improving on hackchi entirely

1. all nes games in working order as well as unlicensed games and japan even unlicensed Korean games like metal force regardless of the games mapper chips
2. remove all glitches and errors on hackchi even the file code error as well as the startup error (meaning i had to download different hackchi versions) entirely
3. unlimited storage meaning no red numbers 
4. fix the nes classic errors
5. and fix the black or gray screen errors entirely

**Comment by DanTheMan827** [comment]
- Are you talking about the C8 error? if so, don't put so many games in a single page.
- NES compatibility through kachikachi (the built-in emulator) can't be improved, use retroarch for incompatible games
- Removing the storage warning makes no sense because you can't magically add space to a system
- Again, what error?
- Don't use the stock emulator for incompatible games.

**Comment by hinson20** [comment]
Well its just that im not that good at stuff like that im just saying they
just need to improve thats all
