### ISSUE TITLE
Just sits on waiting for your mini when loading Kernels

### ISSUE THREAD

**Issue by powerlesshero111** [TeamShinkansen/Hakchi2-CE#400]
**Describe the bug**  
So, basically, just got a genesis mini, and it's just waiting on my mini for connection

**To Reproduce**  
1. Go to kernels, click on install/repair
2. Follow directions to unplug, turn power to on, and plug USB back in while holding reset
3. Just remains on "Waiting for your mini"

**Expected behavior**  
Should readily connect to mini

**Comment by DanTheMan827** [comment]
Do you know of any way to consistently get this to work across system configurations? That would be awesome

The biggest issue people have is driver issues, then if it’s not a driver issue it’s caused by the cable being used

This isn’t the fault of the program, it’s a case of Windows being Windows and just not grabbing the proper driver for RNDIS

**Comment by powerlesshero111** [comment]
I'll try picking up a better cable from Walmart tomorrow. The only one i had extra was for a charging pad, so that might be the problem.

**Comment by DanTheMan827** [comment]
Did the new cable fix this?

**Comment by powerlesshero111** [comment]
Yep. It was a cable issue. Works perfectly now

**Comment by KMFDManic** [comment]
@powerlesshero111 Awesome, have fun with the Mini:)
