### ISSUE TITLE
Mini SNES Can't turn off playing Retroarch

### ISSUE THREAD

**Issue by Farrell39** [TeamShinkansen/Hakchi2-CE#406]
**Describe the bug**  
<I updated recently to use Hakchi CE 3.9.1 and installed Retroarch Core, Nestopia and SNES 2010, and when I'm playing a NES/ SNES game over Retroarch the console don't turns Off when I switch the power button. So, I must switch reset too and immediately appears "SHUTING DOWN..." screen, or must unplug the USB cable.
*No problem with original games runing with canoe.>

**To Reproduce**  

**Additional context**  
Someone could tell me how to fix it?
I already did a factory reset and then reinstall the cores but get same issue.

SNES Mini USA versión.
Hakchi CE 3.9.1
RetroArch 190 Xtreme Ozone or RetroArch 190 Xtreme RGUI (only one of this installed)
Nestopia
Snes9x2010 Xtreme

I would greatly appreciate your help!

**Comment by KMFDManic** [comment]
This isn't a bug.  The "shell" needs to properly close, before you can shut the system off.  Avoid shutting down system, WHILE within a game.  Exit the game to the main menu, THEN turn the system off.  Trying to shut off system while in RetroArch can actually corrupt your saves.  So, consider this a failsafe, to protect your saves.  They are meant to be "saved" upon exit.  Hope that makes sense!  If you were able to shut down while in RetroArch, you would end up getting C8 errors like crazy, depending on the game or Core involved, particularly on the Mini Classics, where things work a bit differently than on PCs:)

**Comment by KMFDManic** [comment]
@Farrell39 For future reference, keep games to a minimum, as far as 30 per folder.  Reinstall RetroArch, if need be.  Micromanage saves, if you have too many.  If system won't shut off, it is usually due to too many games, or corruption (if running USB-HOST).  You can sometimes toggle power off, on, off, to force a shut down.  If that doesn't work, you got way too many games!  Let us know if you need anymore assistance.  Closing this due to lack of response.
