### ISSUE TITLE
when selecting multiple games to be active, the menu freezes, takes a long time...

### ISSUE THREAD

**Issue by G7200** [TeamShinkansen/Hakchi2-CE#58]

**Comment by daPhie79** [comment]
thank you for reporting this issue, it's been reported, and i managed to find the source of the issue! in the meantime, if you want to continue using CE until we release a final version, install sfrom_tool in its dedicated directory. the responsiveness issue is linked with the file not being present. it's a bug and it will be fixed in final release.

**Comment by G7200** [comment]
thanks for helping me out. after putting the sfrom_tool in the directory the menu doesn't freeze anymore!
