### ISSUE TITLE
Always ask to flash custom kernel (v1.2.0RC)

### ISSUE THREAD

**Issue by IvGaLa** [TeamShinkansen/Hakchi2-CE#59]
Hi, i flash a custom kernel with hakchi2 CE v1.2.0. RC, but, when go to "Save-State Manager" allways ask to flash a custom kernel and, when restar hakchi, and go to sincronyze, ask to flash custom kernel too

Is like to no save that i flash a custom kernel later.

I'm on windows 10 and have a SNES mini (Europe)

Thanks

**Comment by DanTheMan827** [comment]
Does the system show as being online in the main window?

Also, make sure you don't have any firewall software blocking hakchi2 ce

**Comment by IvGaLa** [comment]
Hello,
No firewall, but, I have tried again, and now the error does not come out. When I used hackchi2 when clicking on "SAVESTATES" it showed me the message to start the SNES Mini, I thought that with hackchi2 CE it was the same, but no.
I opened hakchi2 CE and started the console (Green "led", not red, in left bottom corner app) and no message appears to flash the kernel.

Thank you

**Comment by daPhie79** [comment]
if your console is not connected and hakchi2 ce cannot detect it (red light), it will default to asking you if you want to flash kernel, because it cannot KNOW that your console is already custom flashed. this is a new behavior, because we have stopped "assuming". just power up your console before attempting operations that require the mini to be turned on!
