### ISSUE TITLE
Support for dropping .zip file containing .cnps

### ISSUE THREAD

**Issue by Mime64** [TeamShinkansen/Hakchi2-CE#63]
I love how the new version supports dropping .cnp files on to hakchi and having them put in the right place, but would it be possible to also allow dropping of a .zip file containing them and have it do the same? The Community Patch Pack, for example, would be perfect if you could just drop the .zip on there.

(I always keep it named snes_patches.zip if that helps, maybe you could look for that name?)

**Comment by daPhie79** [comment]
might add this in the future!

**Comment by ghost** [comment]
this would be really nice, even dropping a .zip containing a .bin is extracting the .bin , need to be changed manually everytime.. (even with u8 (or someting like that) files if there is just one file in the zip.

**Comment by ghost** [comment]
sample for mame2003, weird adding on this one: dragnblz.zip

**Comment by KMFDManic** [comment]
@Mime64 These can be easily put into the sfrom tool/patches folder, in the current incarnation of Hakchi2 CE.  Things will change in the future, relating to better optimization, with the collaboration of DarkAkuma and Team Shinkansen.

@AntiFly I brought this issue to DanTheMan827s attention awhile back, and it has since been fixed:)  Add As-Is, if you hadn't already noticed:)
