### ISSUE TITLE
FRQ | deinstall modules not showing installed modules

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#68]
i got some modules installed from kmfd supplied, 2 days ago there was an update from them so i thought about to update them on my snes mini.
i deleted the old cores from the directory and copied the new one (fyi).

i suggested then i would see the current installed cores like in the origin hackchi but i just see all available.
so it would be much better to see the installed cores when clicking unstall cores. theres no sense to me seeing all available cores (in directory) even there is no possibility to uninstall old cores (in case you do what i did).

so please change feature to display just installed cores/modules on "uninstall modules".
thanks

**Comment by ghost** [comment]
Update: i deinstalled hackchi completely from my snes mini and reinstalled everything again.
now everything is ok.. so maybe this was a glitch because i came over from original hackchi (here i uninstalled the modules first, but didnt do a factory reset).

close it you see there no further need to investigate into it. 
cheers

**Comment by daPhie79** [comment]
the way we build the uninstall list is by looking on the mini itself for uninstall files, so if there were modules not supposed to be there, that's because their uninstall files hadn't been deleted. when you open install modules or remove modules while the mini is turned off, we only display the list of modules currently present in your /user_mods directory.
