### ISSUE TITLE
Shell command "hakchi getBackup2" returned exit code 1

### ISSUE THREAD

**Issue by gingerbeardman** [TeamShinkansen/Hakchi2-CE#81]
Upgrading from 1.1.0 to 1.2.4

The CE update process itself went OK, no issues.

The problems came with it doing things to my SNESC to bring that up-to-date.

After this error, I eventually had to juggle reset/repair a number of times to get things stable.

![screen shot 2018-05-03 at 11 00 54](https://user-images.githubusercontent.com/49612/39576225-598d769e-4ed5-11e8-9ada-f3cbe23dd318.png)

**Comment by DanTheMan827** [comment]
This is a known bug, commit c93a622 actually fixes it.

The problem is caused by the system not having a stock backup available on nand to restore from.

I'm guessing you went directly from 1.1 custom to 1.2.4 custom without restoring to stock in between?

Normally, that wouldn't be an issue, the app under normal circumstances should just prompt when you go to uninstall, but a bug was causing it to throw an exception rather than prompt for the backup.

**Comment by gingerbeardman** [comment]
> I'm guessing you went directly from 1.1 custom to 1.2.4 custom without restoring to stock in between?

yes, I just followed the prompts.

I'll close this and trust that it's fixed.
